import { StyleSheet } from "react-native";
const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: "#f5f5f5",
      justifyContent: "space-between",
      flexDirection: "column",
    },
    header: {
      padding: 20,
      alignItems: "center",
      backgroundColor: "#a1d2f5",
      width: "100%",
      height: 80,
      flexDirection: "row",
    },
    headerText: {
      fontSize: 20,
      fontWeight: "bold",
      color: "black",
      marginLeft: 10,
    },
    arrowleft: {
      color: "black",
      marginTop: 5,
    },
    content: {},
    viewContent: {
      width: "95%",
      backgroundColor: "#e9d8e8",
      borderRadius: 8,
      shadowColor: "#000",
      shadowOpacity: 0.2,
      shadowRadius: 5,
      marginBottom: 10,
      marginTop: 10,
      alignSelf: "center",
    },
    viewRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      paddingVertical: 10, 
      borderBottomWidth: 1, 
      borderBottomColor: "#f1f1f1",
      padding: 5,
      marginHorizontal: 10,
    },
    textTitle: {
      fontSize: 18,
      fontWeight: "600",
      color: "#465c83",
      marginBottom: 8,
      marginLeft: 10,
      marginTop: 10,
    },
    textContent: {
      fontSize: 18,
      marginTop: 10,
      marginRight: 10,
      color: "#465c83",
    },
    textContent1: {
        fontSize: 18,
        fontWeight:'600',
        marginTop: 10,
        marginRight: 10,
        color: "#465c83",
      },
    textContent2: {
      fontSize: 20,
      marginTop: 5,
      marginLeft: 10,
      marginBottom: 5,
      color: "#465c83",
    },
    textContent3: {
      fontSize: 20,
      marginTop: 10,
      marginRight: 10,
      marginBottom: 5,
      marginLeft: 20,
      flexWrap: 'wrap',
      color: "#465c83",
    },
    footer: {
      padding: 16,
      backgroundColor: "#f5f5f5",
      justifyContent: "flex-end",
    },
    btn_create_request: {
      backgroundColor: "#007bff",
      paddingVertical: 12,
      paddingHorizontal: 16,
      borderRadius: 4,
      alignItems: "center",
      justifyContent: "center",
    },
    text_create_request: {
      color: "#fff",
      fontSize: 16,
      fontWeight: "bold",
    },
  });
  export { styles };
  